### ISSUE TITLE
Newline before parenthesis

### ISSUE THREAD

**Issue by OriginLive** [facebook/metro#329] opened 2018-12-11 04:18 UTC
Hello, coming from c++, i'm having a bit of problems with js syntax. Can the following implementation be done:
`class App extends Component
 {

 	render()
	{
 		return
 		( 	// << This line causes the error, putting the parenthesis on a new line
			//code goes here
 		);
 	}
 }`

Basically newline curly braces work, however a parenthesis on a newline does not. It would make sense to keep the same syntax...

Here are two good articles explaining similar problems
https://medium.com/@mwolfhoffman/curly-braces-a-tale-of-two-languages-c-and-javascript-3de81b201b38

http://jamesknelson.com/javascript-return-parenthesis/

**Comment by rafeca** [comment] 2018-12-11 15:32
Hi! Yeah, the two articles that you're linking explain quite well what's going on in this case (it's related with the Automatic Semicolon Insertion (ASI) in JavaScript (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Automatic_semicolon_insertion).

There's not much that Metro can do about this since the code that you posted is valid syntax, but it will have unexpected behaviour (the `render` method will return `undefined`).

I suggest you setting up a linter in your project (`ESLint` is a good one) and configure some rules to writing such code that can have a weird behaviour for people not familiar with the language.

For this specific code, having a rule to [prevent unreachable code](https://eslint.org/docs/rules/no-unreachable) would have catch this error.

Hope this helps 😃 I'm closing this issue since there's not much that Metro can do here

**Closed by rafeca** 2018-12-11 15:32 UTC
