### ISSUE TITLE
React.lazy stopped working in newer metro

### ISSUE THREAD

**Issue by RichardLindhout** [facebook/metro#1019] opened 2023-06-29 18:57 UTC
I have a project in metro@0.73.10 where I use https://www.npmjs.com/package/react-lazy-with-preload, but with newest expo (SDK 49 Beta and newest versions I get the following error when lazy loading/importing components:

js engine: hermes
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot set property 'importedAll' of undefined
TypeError: Cannot set property 'importedAll' of undefined

Versions
metro@0.76.5
react-native@0.72.0

**Comment by RichardLindhout** [comment] 2023-06-29 21:03
```
  "resolutions": {
    "metro": "0.76.0",
    "metro-resolver": "0.76.0"
  }
  ```

Fixed it for me!

**Comment by RichardLindhout** [comment] 2023-07-05 17:16
But react refresh stopped working so I had to downgrade

**Comment by byCedric** [comment] 2023-07-19 16:10
I think I know why it stopped working.

Since this seems to work fine with `0.76.0`, I noticed that @motiz88 changed a few things in [`0.76.1`](https://github.com/facebook/metro/releases/tag/v0.76.1) around async require handling.

[This commit](https://github.com/facebook/metro/commit/4e5261cca6fd84b7ce75f58b038b397b84a4b038) was merged into `0.76.1` and changes the asyncRequire implementation. Basically, the most important change is the [`__loadBundleAsync`](https://github.com/facebook/metro/blob/main/packages/metro-runtime/src/modules/asyncRequire.js#L32-L33) method that actually fetches the async require.

Now, this module is shipped within `react-native` itself ([here to be precise](https://github.com/facebook/react-native/blob/256aaa15bfe1a22044cdedab18ec9db6779f021b/packages/react-native/Libraries/Core/setUpDeveloperTools.js#L78-L80)).

In this Chrome DevTools screenshot below, `loadBundle` method is `undefined`. This makes sense as it's currently not shipped within [`0.72.x`](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/Libraries/Core/setUpDeveloperTools.js#L77).

![image](https://github.com/facebook/metro/assets/1203991/10687041-9420-4a32-8af8-47dbda9f9b1e)

**Comment by byCedric** [comment] 2023-07-20 09:56
To resolve this, you can either disable actual async require handling, or set up the missing `__loadBundleAsync` method through `@expo/metro-runtime`. See [this comment for more info](https://github.com/expo/expo/issues/23570#issuecomment-1642555869).

**Comment by motiz88** [comment] 2023-07-20 10:08
Thanks @RichardLindhout and @byCedric! The bug is that Expo enables `&lazy=true` without always supplying the required runtime piece - Metro is behaving as intended here (see https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0605-lazy-bundling.md#changes-to-the-metro-server).

**Closed by motiz88** 2023-07-20 10:08 UTC

**Comment by NazmusSayad** [comment] 2023-09-17 13:29
> "resolutions": {
>     "metro": "0.76.0",
>     "metro-resolver": "0.76.0"
>   }

This works!
But is there any better way?

**Comment by Jamshdbek** [comment] 2023-11-14 11:47
This is what I put in the app.json file
app.json

`"web": {
      "favicon": "./assets/favicon.png",
      "bundler": "metro"
    },`

this work )
