### ISSUE TITLE
Metro bundler has encountered an internal error

### ISSUE THREAD

**Issue by KnowMighT** [facebook/metro#110] opened 2017-12-28 08:44 UTC
When I run `yarn start` in the terminal and use Expo App to open my RN Project in iPhone,  an error appears as follows:

<img width="412" alt="qq20171228-164317 2x" src="https://user-images.githubusercontent.com/14305694/34405415-3a7683b2-ebee-11e7-81aa-28d2718a04d9.png">

**Comment by rafeca** [comment] 2018-01-02 12:43
Do you have any more information about the error? Any log shown on the terminal would help

**Comment by KnowMighT** [comment] 2018-01-03 11:39
There is only `Failed building JavaScript bundle` on the terminal. I can successfully run on Android but fail on iOS, neither iPhone or simulator. 

I'm not sure that this problem is caused by `metro`. I created a new project and encountered the same problem, so maybe not code itself.

**Comment by qsmrf56** [comment] 2018-01-07 13:41
Ok so I was having the same issue but I just restarted my IDE, command line and ran the app again it worked fine.

**Comment by onpaws** [comment] 2018-01-09 16:00
Decided to try Expo today for the first time since last summer. Was eager to see what's new.
Started with `exp init`, chose the 'blank' app, followed by `exp start`
Installed Expo on my physical iPhone and attempted to connect via QR code.
Unfortunately got the same error as OP on physical iPhone.
Couldn't get Simulator to connect to Expo either.
I didn't try Android.

It's a real shame that literally the first Expo experience is a blocking error.
I'm sure there's some good work available here but I don't have time to waste.
At least the old school way works - going back to that. 

I wish the Expo team good luck, I know this project has potential to save time but right now the project's default experience is broken for me.

**Comment by mkrn** [comment] 2018-01-10 12:39
This appears to be something very new, I haven't seen a problem like that before. Started out of nowhere, no helpful logs..
![image](https://user-images.githubusercontent.com/1870075/34773353-c0b28adc-f5e1-11e7-8cda-2ca7aa012274.png)

**Comment by vincekruger** [comment] 2018-01-11 09:41
I'm having the same problem. :(
I also do not have any interesting logs.  http://snack.expo.io works perfectly with the same project.

![img_0835](https://user-images.githubusercontent.com/360833/34818686-3bf14a3e-f6c4-11e7-8404-750d1b411deb.PNG)

**Comment by baldurpan** [comment] 2018-01-11 21:48
Same problem here.

**Comment by onpaws** [comment] 2018-01-14 18:38
@vincekruger Thanks for mentioning that about Snack working.
I was able to get things started that way at least. While a web IDE is far from ideal at least it's something.

**Comment by onpaws** [comment] 2018-01-14 18:40
@rafeca The out of the box experience is broken for me and these other folks, and coming up on a week with no response. Would appreciate your opinion here :)

**Comment by rafeca** [comment] 2018-01-15 11:23
Hey people! I'd need some more specific logs/repro steps in order to investigate this.

I've tried to reproduce it in React Native v0.52 with my test app (https://github.com/rafeca/rn-test-app) and I cannot see such error, so this may be an issue with the expo CLI integration.

**Comment by onpaws** [comment] 2018-01-15 16:28
Thanks for checking @rafeca!
Seeing as it's apparently specific to Expo, I'll be happy to pass the issue over there.

The problem is the Expo folks have disabled their [issue tracker](https://github.com/expo/exp) on GH.
If anyone here happens to know their preferred channel to file bugs, or their Slack, etc I'll be happy to pass this along.

**Comment by onpaws** [comment] 2018-01-15 16:29
Posting a new issue [here](https://github.com/expo/expo/issues) in the meantime

**Comment by brentvatne** [comment] 2018-01-15 17:16
I suspect there is some bug with npm 5 causing problems for people here, but nobody here actually provides steps to reproduce the problem so it's hard to say (as it works as expected for me and many thousands of other people). Please use npm 4 `npm i -g npm@4` or yarn (https://yarnpkg.com/en/docs/install).

**Comment by onpaws** [comment] 2018-01-15 17:56
Over on the [Expo thread I opened](https://github.com/expo/expo/issues/1260), Brent recommended using yarn because npm5 apparently still has bugs.

In my case, even though I don't recall using npm to install `exp`, I nevertheless did a 
`npm uninstall -g exp` followed by
`yarn global add exp`

and I'm back in business. 
If you get a chance to try this, please post back if it worked for you.

Hope it helps!

**Comment by martonczirjak** [comment] 2018-01-18 11:50
I had the same issue, npm start -- -- reset-cache solved it, if it says cant run on port **** kill thoose process and reset again

**Comment by KnowMighT** [comment] 2018-01-21 11:45
@marcinkosiba it doesn't work for me : (

**Comment by KnowMighT** [comment] 2018-01-21 13:15
@onpaws Thanks for investigating this problem. I have tried to `npm uninstall -g exp` followed by
`yarn global add exp`, but it also doesn't work for me. 
I think I'd go crazy！😭

**Comment by serdarde** [comment] 2018-01-25 11:42
React Native doesn't work with **NodeJS 9** and new version of NPM
You have to downgrade your NodeJS version or you can use NVM to set different node version for each terminal: https://github.com/creationix/nvm

Downgrade your node version to: 8.9
and your NPM version to: 4.6.1

**Comment by fiveinfinity** [comment] 2018-01-25 16:25
It doesn't appear to work with ANY version of node & npm.

**Comment by nukes88** [comment] 2018-01-27 00:44
Yeah same issue with me, i’ve tried using npm3.10.10 still the same, create new project, run on device (genymotion or even on iOS), get the metro bundler internal error

**Comment by GentryRiggen** [comment] 2018-01-29 04:22
Fam,
I fixed my issue and like most of them, it's completely my fault. I was refactoring and deleted some files without cleaning up some imports of the deleted files. The only way I found this was to add a console.log in metro (node_modules/metro/src/lib/formatBundlingError.js).

`function formatBundlingError(error) { console.log(error); }`

**Comment by onpaws** [comment] 2018-01-29 15:40
I just made a curious discovery.
I had a plus character -- '+' -- in the absolute path to my project folder, e.g.
`/Users/pat/projects/+ReactNative/MyExpoProject`

I changed to
`/Users/pat/projects/MyExpoProject`
restarted everything,
and we're off to the races.

**Comment by onpaws** [comment] 2018-01-29 15:45
Anyone else have non-alphanumeric character in your absolute path?
Be curious to hear any reports of this working or not.

**Comment by qgadrian** [comment] 2018-01-29 19:51
@onpaws I don't have any non-alphanumeric in my project path, and I got this error suddenly, without any specific change..

I removed the `node_modules` folder and run `yarn` and everything looks fine now.

I'm using the [snackbar dialog library](https://github.com/9gag-open-source/react-native-snackbar-dialog) and I have to run `yarn build` inside the dependency [since they have a bug](https://github.com/9gag-open-source/react-native-snackbar-dialog/issues/33#issuecomment-352872129) in the code. Just a disclaimer, maybe it's related, maybe it's not.

**Comment by KnowMighT** [comment] 2018-01-30 11:51
@onpaws I tried to create a new project in the path which doesn't has  non-alphanumeric character, it finally worked!  lol 

In my old project, there is  non-alphanumeric characters in its absolute path. I  ran `yarn start` in the terminal just now and found error as follows. it's caused by  `React%20Native (React Native)` ！

![274918dc-ce21-433f-82e0-8d2b8d64fa8c](https://user-images.githubusercontent.com/14305694/35563974-88a07394-05f3-11e8-8e73-f9c406651790.png)

**Comment by onpaws** [comment] 2018-01-30 15:16
@KnowMighT Glad it worked for you!

**Comment by xtebs** [comment] 2018-02-03 14:35
On my side this error was caused by incompatible Expo <--> React-native versions (After upgrading expo) and it is solved now.  
Here are the compatibilities: https://docs.expo.io/versions/latest/sdk/index.html
 -I replaced (e.g) the version of sdkVersion": "24.0.0" on app.json and expo "24.0.0" and  react-native 0.51.0 (exact version)on package.json.
- Delete all node_modules and reinstall everything (npm install). 
Let me know if this solves your problems.

**Comment by misaal9** [comment] 2018-02-18 04:24
I suddenly started getting this error (Module bundler has encountered...) ever since I started using [`react-navigation-addons`](https://github.com/satya164/react-navigation-addons) package. I updated my Expo versions on both ios simulator as well as XDE (latest @49.2.2), but that didn't solve the problem. I used yarn to add latest exp globally. Removing this `react-navigation-addons` package does not give me the error anymore.

As per some of the comments above, I'll try playing around with different versions of `react-native` (currently @0.52.0) to see if that helps.

**Comment by dennisja** [comment] 2018-02-27 11:24
I got the same error and when I checked my error log this is the error:
```
error: bundling failed: Error: While trying to resolve module `react-native-vector-icons` from file `/Users/dj/Desktop/learn/react-native/crm/src/components/PersonItem.js`, the package `/Users/dj/Desktop/learn/react-native/crm/node_modules/react-native/local-cli/core/__fixtures__/files/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/dj/Desktop/learn/react-native/crm/node_modules/react-native/local-cli/core/__fixtures__/files/index.js`. Indeed, none of these files exist:

  * `/Users/dj/Desktop/learn/react-native/crm/node_modules/react-native/local-cli/core/__fixtures__/files/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/Users/dj/Desktop/learn/react-native/crm/node_modules/react-native/local-cli/core/__fixtures__/files/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ResolutionRequest.resolveDependency (/Users/dj/Desktop/learn/react-native/crm/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:108:15)
    at DependencyGraph.resolveDependency (/Users/dj/Desktop/learn/react-native/crm/node_modules/metro/src/node-haste/DependencyGraph.js:269:4352)
    at /Users/dj/Desktop/learn/react-native/crm/node_modules/metro/src/DeltaBundler/traverseDependencies.js:201:36
    at Generator.next (<anonymous>)
    at step (/Users/dj/Desktop/learn/react-native/crm/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:306)
    at /Users/dj/Desktop/learn/react-native/crm/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:536
    at new Promise (<anonymous>)
    at /Users/dj/Desktop/learn/react-native/crm/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:217
    at addDependency (/Users/dj/Desktop/learn/react-native/crm/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:92)
    at /Users/dj/Desktop/learn/react-native/crm/node_modules/metro/src/DeltaBundler/traverseDependencies.js:237:9
```

Its like its due to react-native-vector-icons package in my case.
I'm not using expo

**Comment by brentvatne** [comment] 2018-02-27 15:32
I found that this can be due to assets in some cases, in particular when attempting to do a minified dev=false build. I had to clear the cache for it to go away (using exp, `exp start -c`)

**Comment by beormalte** [comment] 2018-03-02 11:05
easiest fix for me is 
killall node -9

**Comment by mrcflorian** [comment] 2018-03-26 04:14
Luckily, I fixed this by mistake. Posting here in case it'll help with the fix. Changing

"import NavigationBar from "./../../../components/common/";"
to
"import NavigationBar from "./../../..//components/common/";"

works.

(so adding an extra / before "components")

The first path is absolutely correct.

**Comment by har2008preet** [comment] 2018-03-28 11:40
in my case, i didn't had sdk location in local.properties

**Comment by austinyearlykim** [comment] 2018-04-11 04:24
npm installing modules without restarting expo XDE was the culprit for me, hope this helps






also, if you're reading this; you are loved and don't let anybody tell you otherwise <3

**Comment by rafeca** [comment] 2018-04-11 08:13
Hey people, I'm going to close this issue, since it seems mostly related to expo (so the discussion is more relevant in https://github.com/expo/expo/issues/1260)

**Closed by rafeca** 2018-04-11 08:13 UTC

**Comment by gersonmontenegro** [comment] 2018-06-05 02:54
reinstall exp works for me

**Comment by MrChristofferson** [comment] 2018-07-27 00:21
Just in case anyone else finds themselves here, my solution (after several hours) to this exact error prompt was from VSCode sneakily importing:
`import { Platform } from '../../node_modules/@types/react-native';`
at the top of _one_ file amongst other imports. When it should obviously be:
`import { Platform } from 'react-native';`

**Comment by geocfu** [comment] 2018-11-21 23:48
I had the same issue.
I am using react native ver. 0.57.
In my case, i dont use expo.
How i resolved it:
```
rm -rf node_modules/
```
```
npm install
```
```
react-native link
```
```
react-native run-android
```
for ios replace 
```
run-android
```
with
```
run-ios
```

**Comment by shmilyiselephant** [comment] 2018-12-27 14:13
> I had the same issue, npm start -- -- reset-cache solved it, if it says cant run on port **** kill thoose process and reset again

Thank you for the answer! It works for me.

**Comment by musicmeetscode** [comment] 2019-02-05 20:02
I have the same issue, been about two weeks now. And ive noticed it appeared when i updated my expo

**Comment by kevin11h** [comment] 2019-02-15 23:08
@KnowMighT Jayesh wrote a blog detailing potential solutions

https://www.c-sharpcorner.com/blogs/react-native-common-errors

How is your developing working now?

**Comment by mr-niri** [comment] 2019-02-23 05:52
I have same problme with RN version "0.58.2" on ubuntu 18.04 LTS
I can fixed the problme just by openning the terminal and cd to project folder and run sudo npm start .

**Comment by konyan** [comment] 2019-03-12 14:01
I have same problem with RN 0.59 on Mac 
This error occurs , u are upgrading gradle 3.3.1 to 4.0.0 or something 

RN default support 3 version
 >classpath 'com.android.tools.build:gradle:3.3.1'

while u open project in Android Studio , its show dialog of Auto Update gradle, u need to skip this dialog.

**Comment by PradeepLinkites** [comment] 2019-03-20 11:08
> npm start -- -- reset-cache

Thanks a lot...it works

**Comment by subhashchandrujobop** [comment] 2019-05-11 07:46
Make sure 
you have properly imported all the component because in my case that was the fault

**Comment by RONAKDHOLARIYA** [comment] 2020-05-27 06:25
remove all files from C:\Users\<your pc name>\AppData\Local\Temp

**Comment by ccksfh** [comment] 2020-09-22 09:51
> remove all files from C:\Users<your pc name>\AppData\Local\Temp

this works for me！！thanks！save my day

**Comment by joaoruirego** [comment] 2021-09-03 01:35
That error appeared to me because when importing I wrote on terminal "nom start react-native-animatable --save", just by removing the "save" part, I was able to get it all working nicely

**Comment by johnphealipto** [comment] 2023-12-02 08:58
> I had the same issue, npm start -- -- reset-cache solved it, if it says cant run on port **** kill thoose process and reset again
Thank you for this, it really fixed the issue. But in my own case I had to use the command below:
`npx expo start -- --reset-cache`
