### ISSUE TITLE
Images with @2x or @3x in their file names are not resolved (breaks static image resources)

### ISSUE THREAD

**Issue by mo-solnet** [facebook/metro#43] opened 2017-08-21 04:38 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a *bug*

**What is the current behavior?**

Images with `@2x` or `@3x` in the file name are not resolved when doing `require('../myImage@2x.png')`. If I remove the `@` then it loads the file without an issue.

![image](https://user-images.githubusercontent.com/30223210/29503629-779c37f8-868d-11e7-8c8a-82b62ef438aa.png)

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**

Others have reproduced this behavior as you can see 👉  https://github.com/facebook/react-native/issues/15030

**What is the expected behavior?**

I expect the files to load and be resolved without an issue. This problem breaks static image resources 👉 https://facebook.github.io/react-native/docs/images.html#static-image-resources

**Please provide your exact metro-bundler configuration and mention your metro-bundler, node, yarn/npm version and operating system.**

I've used the stock version that comes with `react-native 0.47.1`. 
I've also tried `--reset-cache` and finally I've also updated metro-bundler to version `0.11.0`.
`npm`  5.0.3
`yarn`  0.27.5
`Mac OSX` 10.12.6

The only workaround I've found is to remove the `@` when requiring the file

**Comment by cpojer** [comment] 2017-10-09 09:56
@jeanlauliac knows about assets.

**Comment by jeanlauliac** [comment] 2017-11-14 11:17
Sorry I've been lagging behind quite a lot.

About this issue: in Metro, assets are not meant to be required with a specific scale, since different devices might use different scales. In that example, requiring `./myImage.png` would cause either `myImage@2x.png` or `myImage@3x.png` to be used depending on the device screen pixel ratio (virtual-pixel to physical-pixel ratio, so to speak).

@mo-solnet can you explain what is the benefit of using `require('../myImage@2x.png')` over `require('../myImage.png')`?

**Comment by jasperkuperus** [comment] 2017-12-11 10:52
@jeanlauliac Is it an idea to add a better error if someone does use `@2x` and then refer to this issue?

**Comment by jeanlauliac** [comment] 2017-12-11 12:04
Yes, a specific error message sounds good to me. I would not refer to this issue though, I'd just mention that removing the specific solves the problem.

**Comment by jeanlauliac** [comment] 2018-01-10 14:44
I haven't got the time to try to fit a hint message somewhere in the stack, but I'll close this issue for now, as this is the expected behaviour, and scale specifiers should not be included in the name when requiring assets. Do feel free to send a PR to tweak error messages however.

The documentation mentions having different densities and does have the example without the density specifier, so I don't think it needs updating? (https://facebook.github.io/react-native/docs/images.html#static-image-resources)

**Closed by jeanlauliac** 2018-01-10 14:44 UTC
