### ISSUE TITLE
HELP error index.js: The "id" argument must be of type string. Received undefined.

### ISSUE THREAD

**Issue by walidhousni30** [facebook/metro#1017] opened 2023-06-27 21:12 UTC
### Description

Since i upgraded my react native app to 0.72 i cant run the app anymore .i ve tried to dedupe the duplicates of metro , but here i am stuck with this error .

<img width="1440" alt="image" src="https://github.com/facebook/react-native/assets/109111644/c41af11f-4aae-41bf-b172-2cc2ade28cef">

### React Native Version

0.72.0-rc.6

### Output of `npx react-native info`

System:
  OS: macOS 13.4
  CPU: (8) arm64 Apple M1
  Memory: 126.47 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.3.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 4.0.0-rc.45
    path: ~/Desktop/projects/labelvie/fid-mobile-copy/node_modules/.bin/yarn
  npm:
    version: 9.6.7
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.06.12.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/walidhousni/.rvm/gems/ruby-3.2.2/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "31"
      - "33"
    Build Tools:
      - 30.0.2
      - 30.0.3
      - 33.0.0
      - 33.0.2
      - 34.0.0
    System Images:
      - android-33 | Google TV Intel x86 Atom
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/walidhousni/.rvm/rubies/ruby-3.2.2/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 10.0.0
    wanted: 10.0.0
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.0-rc.6
    wanted: 0.72.0-rc.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

react-native start --reset-cache

### Snack, code example, screenshot, or link to a repository

import { AppRegistry, Platform } from 'react-native';
import App from './src/App';
import { name as appName } from './app.json';

// Here, we require "intl", which is used in @lingui/macro, but not available in Hermes (used for Android)
if (Platform.OS === 'android') {
  global.Intl = require('intl');
  require('intl/locale-data/jsonp/fr.js');
  require('intl/locale-data/jsonp/en.js');
  // add more locales
}

AppRegistry.registerComponent(appName, () => App);

**Comment by cortinico** [comment] 2023-06-28 10:10
Moving this over to facebook/metro for furhter investigation as I see `metro-transform-worker` as part of the stacktrace

**Comment by walidhousni30** [comment] 2023-06-28 10:13
where did you see metro-transform-worker ??

**Comment by walidhousni30** [comment] 2023-06-28 10:43
@huntie  here's the content of metro.config.js 


`const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
const path = require('path');
/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  watchFolders: [path.resolve(__dirname, '../../')],
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
  resolver: {
    sourceExts: ['js', 'jsx', 'ts', 'tsx', 'mjs'],
    resolverMainFields: ['sbmodern', 'react-native', 'browser', 'main'],
  },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
`

**Comment by huntie** [comment] 2023-06-28 12:09
From the line numbers reported in the stack trace, it looks like while you're on `metro@0.76.5`, you have [`metro-transform-worker` 0.71.1 or older](https://unpkg.com/browse/metro-transform-worker@0.71.1/src/index.js#L410) installed.

Please can you run the below and share the result here?

```sh
yarn why metro-transform-worker
```

I also note that you are depending on an old version of React Native CLI — React Native 0.72 requires (and depends on) `@react-native-community/cli@11.3.2`.

```
npmPackages:
"@react-native-community/cli":
installed: 10.0.0
wanted: 10.0.0
```

⬆️ Sometimes, this can be caused by installed libraries which (problematically) depend on `react-native` directly. It could also be from forced dependency versions (e.g. Yarn `resolutions` — please revert these).

To be sure your dependencies are as specified, try also:

```sh
rm -rf node_modules
yarn
```

**Comment by walidhousni30** [comment] 2023-06-28 12:24
thank you for your clear and consistent answer 

here's the yarn why metro-transform-worker log
`├─ metro@npm:0.70.4
│  └─ metro-transform-worker@npm:0.70.4 (via npm:0.70.4)
│
├─ metro@npm:0.73.10
│  └─ metro-transform-worker@npm:0.73.10 (via npm:0.73.10)
│
└─ metro@npm:0.76.5
   └─ metro-transform-worker@npm:0.76.5 (via npm:0.76.5)`

**Comment by huntie** [comment] 2023-06-28 14:44
@walidhousni30 Great — worth digging up why `metro@npm:0.70.4` is there (old version), by trying `yarn why metro` etc. Really, there should only be one version of Metro (`metro@npm:0.76.5`) in your project.

**Comment by walidhousni30** [comment] 2023-06-28 14:47
@huntie i did yarn why metro but i dont know exactly how to get rid of the duplicates / old versions

**Comment by walidhousni30** [comment] 2023-06-28 20:11
@huntie  what do i need to do afterwards , please if you can provide any help ?

**Comment by bartolkaruza** [comment] 2023-06-29 06:20
I had the same issue just now, the solution was removing `"metro-config"` from `"dependencies": {}`. (not dev-dependencies)

![Screenshot 2023-06-29 at 06 19 41](https://github.com/facebook/metro/assets/1605731/8aa72d65-5390-49c2-82ea-12ecac36b784)

**Comment by huntie** [comment] 2023-06-29 11:05
@walidhousni30 It looks like `flipper-server` and `flipper-pkg-lib` are the dependencies bringing in an older version of Metro. Is this a dependency you can update or eliminate?

Do also try:
- Removing any explicit `metro` dependencies or devDependencies in your project's `package.json` (per @bartolkaruza's fix).
- **As a fallback**, using [Yarn `"resolutions"`](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to force the current version of Metro: `0.76.5`.

**Comment by walidhousni30** [comment] 2023-06-29 11:59
@bartolkaruza  i have it only on my dev dependency like so 
![image](https://github.com/facebook/metro/assets/109111644/e613e338-5e25-4030-b32b-f3b0d51bfd65)

i will try huntie method as well so i could force the 0.76.5 metro version

**Comment by walidhousni30** [comment] 2023-06-29 12:06
@huntie  MAAAAN ITT WOOOORKS THANK YOU SOOO MUCH 
@bartolkaruza  your method works as well i cant thank you enough guys

**Comment by bartolkaruza** [comment] 2023-06-29 12:07
> @bartolkaruza i have it only on my dev dependency like so
even if it's in your dev dependencies, it may cause this issue. Try removing it entirely from package.json, then `yarn install` to clear it from node_modules

**Comment by bartolkaruza** [comment] 2023-06-29 12:07
I commented too soon, glad it's working for you!

**Closed** 2023-06-29 12:25 UTC

**Comment by walidhousni30** [comment] 2023-06-29 19:27
> I commented too soon, glad it's working for you!

You can imagine i ve spent 2 weeks just trying to find out which module was causing all of this mess after upgrading it

**Comment by KareemWilson** [comment] 2023-07-17 12:11
@walidhousni30 I have the same problem, but I can't solve it :(

**Comment by uladzislau-stuk** [comment] 2023-08-14 18:20
I have just migrated to 72.4 and started getting the same error. Downgrading @react-native/metro-config to 0.72.9 helped me.

With @react-native/metro-config 0.72.1 I get the following error when building the project:

`
TypeError: The "id" argument must be of type string. Received undefined
error index.js: The "id" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Module.require (node:internal/modules/cjs/loader:1150:3)
    at require (node:internal/modules/helpers:119:18)
    at transformJS (/Users/macpc/Downloads/Projects/EdgeMobile/node_modules/metro-transform-worker/src/index.js:227:35)
    at transformJSWithBabel (/Users/macpc/Downloads/Projects/EdgeMobile/node_modules/metro-transform-worker/src/index.js:364:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.transform (/Users/macpc/Downloads/Projects/EdgeMobile/node_modules/metro-transform-worker/src/index.js:510:12)
`

**Comment by aanagalli** [comment] 2023-09-18 20:38
I confirm @uladzislau-stuk  comment. Today I created a new project and I was having the same error. Downgrading @react-native/metro-config to 0.72.9 worked fine.

**Comment by CaptainJeff** [comment] 2023-11-10 19:29
Removing metro-config fixed it for me too

**Comment by meraezekiel** [comment] 2023-11-28 06:40
Thank you so much ! i just copy the added packages (color green) aside from "react-native-windows" , it works ! . This is the link below where i follow the solution

https://github.com/lovegaoshi/azusa-player-mobile/commit/84a779ff0158474951ab12a06c129a5b873763eb

**Comment by benohiit** [comment] 2024-10-10 09:30
`npm install @react-native/metro-config@0.72.9 --dev ` worked for me on android, but not on ios until I updated `npm install @react-native-community/cli@11.3.2 --dev` thanks @huntie
