### ISSUE TITLE
Metro error: Cannot find module 'react'

### ISSUE THREAD

**Issue by jason-slatt** [facebook/metro#1388] opened 2024-11-14 15:28 UTC
i have the error << Metro error: Cannot find module 'react' >> i have react installed , and all the dependencies 

i tried deleted my node_modules and the package-lock.json 

and reinstall everything still got the same problemn

**Comment by vpaul18** [comment] 2024-11-15 10:47
having the same problem

**Comment by nmnb18** [comment] 2024-11-20 13:00
Having the same problem? Any update?

**Comment by khayrullaev** [comment] 2024-11-20 13:12
any updates?

**Comment by robhogan** [comment] 2024-11-20 14:10
Could anyone share any details about this? The issue template has been ignored and there's nothing to go on here.

 - React Native and Metro version
 - Package manager
 - Expo or Community CLI project
 - Ideally, how we'd reproduce this problem from scratch, or a repository that reproduces it

**Comment by daledesilva** [comment] 2024-11-29 05:19
Okay... I re setup the eas project in various folders and found out that the issue (At least for me), is due to spaces in the paths.
ie. I had
```/Projects (External)/My Project/git-folder```
But changing the folder names to the below fixes it:
```/Projects(External)/MyProject/git-folder```

Frustrating that is the problem but I'm just going to have to adapt.
Hopefully this helps someone else.

**Comment by hikaripurin0426** [comment] 2024-12-06 02:33
Thank you very much. You've saved my life.

**Comment by CesarsEren** [comment] 2024-12-08 20:06
Thank you very much, those are the spaces in the foldernames.

**Comment by robhogan** [comment] 2024-12-08 20:08
Is this only on Expo/EAS or is anyone seeing this in a community CLI project?

Spaces should be fine, this is a bug somewhere.

**Comment by robhogan** [comment] 2024-12-10 22:56
Confirmed this is an Expo EAS issue - in fact the error isn't even thrown by Metro. The path created here:

https://github.com/expo/expo/blob/d8dd52485bc0f67b5e054b2d41a3ea28856f1c41/packages/%40expo/cli/src/start/server/middleware/metroOptions.ts#L268

Will URL-encode spaces (and others). That then gets passed as `filename` to here:

https://github.com/expo/expo/blob/d8dd52485bc0f67b5e054b2d41a3ea28856f1c41/packages/%40expo/cli/src/start/server/getStaticRenderFunctions.ts#L129

Where `require-from-string` can't resolve any local packages (including `react`) successfully because the origin path is wrong (contains unexpected percent-encodings), so the `node_modules` lookup paths are wrong, and resolution fails.

CC @byCedric

**Comment by robhogan** [comment] 2024-12-10 22:59
Closing this here, but folks experiencing this should open an Expo issue (and point Cedric at the comment above ;))

**Closed by robhogan** 2024-12-10 22:59 UTC

**Comment by oyerohabib** [comment] 2025-01-29 16:22
> Okay... I re setup the eas project in various folders and found out that the issue (At least for me), is due to spaces in the paths. ie. I had `/Projects (External)/My Project/git-folder` But changing the folder names to the below fixes it: `/Projects(External)/MyProject/git-folder`
> 
> Frustrating that is the problem but I'm just going to have to adapt. Hopefully this helps someone else.

This fixed my issue. I have a parent folder that had space inbetween. Thank you very much!

**Comment by lukebrandonfarrell** [comment] 2025-02-10 11:50
@oyerohabib You sir, are a live saver ❤️

**Comment by oyerohabib** [comment] 2025-02-10 13:19
> [@oyerohabib](https://github.com/oyerohabib) You sir, are a life saver ❤️

I am glad it helped you. Well done!

**Comment by xk3rn3lp4n1c** [comment] 2025-03-08 01:48
> Okay... I re setup the eas project in various folders and found out that the issue (At least for me), is due to spaces in the paths. ie. I had `/Projects (External)/My Project/git-folder` But changing the folder names to the below fixes it: `/Projects(External)/MyProject/git-folder`
> 
> Frustrating that is the problem but I'm just going to have to adapt. Hopefully this helps someone else.

Thanks bro!
