### ISSUE TITLE
Metro bundler fails when useWatchman is false

### ISSUE THREAD

**Issue by daniel-azu** [facebook/metro#868] opened 2022-09-15 10:19 UTC
Getting the following error:
```
error Invalid platform "ios" selected.
error Bundling failed.
```
I put it under config file in the following structure:
```
{
    "resolver": {
        "useWatchman": false
    }
}
```

**Comment by robhogan** [comment] 2022-09-22 14:39
Hi @daniel-azu - it looks like you're probably overriding the `resolver.platforms` option somehow.

Can I check that you're adding the option within `metro.config.js` at the root of your React Native(?) project, and if so could you post your complete `metro.config.js` please, along with the output of `npx react-native info`?

**Comment by robhogan** [comment] 2022-10-03 10:07
I can't reproduce this as-is so I'm closing, but please reopen or file a new issue if you can share a repro case.

**Closed by robhogan** 2022-10-03 10:07 UTC
Labels: Needs: Environment Info
