### ISSUE TITLE
Importing files outside project directory does not work

### ISSUE THREAD

**Issue by bojan96** [facebook/metro#269] opened 2018-09-27 11:57 UTC
My folder structure is this:

```
ReactNativeTest
 |---   Lib/
 |         |--- lib.js
 |---   ReactNativeTest/
           |--- App.js
           |--- app.json, index.js, ...
   
```
Lib is shared between many projects

Inside App.js
`Import lib from ../Lib/lib; `
Currently metro has issue with [symlinks ](https://github.com/facebook/metro/issues/1)in node_modules folder, so I thought why not include shared library using relative path, but this does not work either

> error: bundling failed: Error: Unable to resolve module `../Lib/lib` from `D:\Projects\ReactNativeTest\ReactNativeTest\App.js`: The module `../Lib/lib` could not be found from `D:\Projects\ReactNativeTest\ReactNativeTest\App.js`. Indeed, none of these files exist:
>   * `D:\Projects\ReactNativeTest\Lib\lib(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
>   * `D:\Projects\ReactNativeTest\Lib\lib\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`

In the end, I solved this issue by copying Lib dir to RN project dir, and importing from './Lib/lib' but this is not ideal solution.
OS: Windows 10

**Comment by rafeca** [comment] 2018-10-01 09:45
Hi!

Metro has a config param where you can define folders that are outside of your `projectRoot`: it's called `watchFolders`. There's more information about it and other config params in: https://facebook.github.io/metro/docs/en/configuration#general-options

Closing the issue, please reopen if this does not solve it 😃

**Closed by rafeca** 2018-10-01 09:45 UTC

**Comment by ivan-jorge001** [comment] 2018-10-10 22:48
this doesn't work for me, I have the same project structure and when I import a js file it works perfectly but now if I import anything that isn't a .js (like png, svg, jpg) file it breaks, it doesn't display any error but just doesn't show the image. If put them within the project root then it works perfectly. please let me know if you need further details

**Comment by aleclarson** [comment] 2018-10-19 12:14
@ivan-jorge001 I would recommend reproducing the bug in a minimal repository if this is important to you.

**Comment by marioharper** [comment] 2018-11-02 16:14
@rafeca looks like this does not work with `.jpg`'s like @ivan-jorge001 pointed out above. I'll create a reproducible project and link it in #289.
