### ISSUE TITLE
Packager error: "Can't find variable: process"

### ISSUE THREAD

**Issue by richardgirges** [facebook/metro#73] opened 2017-10-10 16:27 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**Behavior**
The issue was initially discovered in #65 after people began using the latest metro-bundler 0.20.0 version to work around dynamic requires in packages like moment.js

Packager throws the following error when bundling:
```
Unhandled JS Exception: Can't find variable: process
```

**Repro Steps**
1. Add metro-bundler 0.20.0 to package.json as a "resolutions" entry for react-native:
```
"resolutions": {
  "react-native/metro-bundler": "0.20.0"
}
```

2. Run `react-native run-ios` as normal.

NOTE: The fact that this issue manifested for people in metro-bundler@0.20.0 is a red herring. This issue appears to be happening with older versions of metro-bundler as well. I've confirmed the same error appears in metro-bundler@0.19.0. I haven't tried to reproduce it in any versions older than 0.19.0 yet. 

**Environment**
Node: v8.5.0

package.json
```
  "dependencies": {
    "react": "16.0.0-beta.5",
    "react-native": "0.49.3"
  },
  "resolutions": {
    "react-native/metro-bundler": "0.19.0"  
  },
```

**Comment by tqc** [comment] 2017-10-10 21:07
I ran into that one last week. It seems to be related to the order things get packaged in - react native polyfills process.env, but does it after react tries to check if it is running in dev mode.

Putting the first RN import before the first react import seems to have fixed it, but it was working fine the other way around on previous versions.

**Comment by cpojer** [comment] 2017-10-10 21:38
Would be good to figure out which module is throwing this.

**Comment by tqc** [comment] 2017-10-10 22:12
In my case it was react - unlike #65 it’s not just a bundler setting/ error message. Were previous releases perhaps effectively hardcoded to load react native before anything else?

**Comment by mackenziemance** [comment] 2017-10-10 23:37
Any updates on this ?, moment 2.19.0 has been reverted so that fix isn't an option.

**Comment by brunocascio** [comment] 2017-10-11 03:32
Please, take a look at this issue.

**Comment by fungilation** [comment] 2017-10-11 06:29
Since [moment is reverting](https://github.com/facebook/metro-bundler/issues/65#issuecomment-335615159) their fix, a fix in Bundler would be appreciated!

**Comment by zuoge85** [comment] 2017-10-12 03:13
+1

**Comment by romreed** [comment] 2017-10-12 09:10
Any changes?

**Comment by tsyeyuanfeng** [comment] 2017-10-17 02:43
`process` is set up in `InitializeCore` module of `react-native`.
```
// InitializeCore.js
// Set up process
global.process = global.process || {};
global.process.env = global.process.env || {};
if (!global.process.env.NODE_ENV) {
  global.process.env.NODE_ENV = __DEV__ ? 'development' : 'production';
}
```
So `InitializeCore` module must run before entry module. Previously, `runBeforeMainModule` config was specified in  `defaults.js` where `InitializeCore` is included. But it has been removed from `metro-bundler` in this commit [Make the runBeforeMainModule config param to RN repo and make it absolute](https://github.com/facebook/metro-bundler/commit/eefb8e9fc5c3c5d6f3956e970b1771f3af3edc4a) recently. However, it seems that there are some problems with this commit, I've created another issue #78  to disscus about this.

**Comment by tqc** [comment] 2017-10-17 02:59
@tsyeyuanfeng That would explain why things suddenly stopped working.

See also the corresponding RN commit https://github.com/facebook/react-native/commit/34487c059192129db07608af4eb27cfad22b2d06

Looks like that commit isn’t part of 0.49, but is tagged as v0.50.0-rc0 - it will work just fine with facebook’s internal setup (master of both in a single repo) but the open source dependencies are broken at the moment.

**Comment by amardeepranu** [comment] 2017-11-08 00:54
Getting this error when trying to run on a device on RN v0.50.2

**Comment by blackxored** [comment] 2017-11-08 07:00
Can confirm that 0.50.2 has this error. It only happens on release build for me though.

**Comment by JuliusMalisauskasDB** [comment] 2017-11-08 10:19
I have this issue too on 0.50.2. Is there any workarounds?

**Comment by rafeca** [comment] 2017-11-08 11:21
We have just released metro-bundler v0.20.2, which should solve this issue. Can somebody confirm?

**Comment by JuliusMalisauskasDB** [comment] 2017-11-08 13:57
It seems to fix Debug build (which can be run on ios devices now), however there is another Release build issue now:
https://github.com/facebook/react-native/issues/16745

**Comment by PvanHengel** [comment] 2017-11-08 15:17
We are seeing the same release build issue in ios, we didn't have any issues with the debug build.    The ```Unhandled JS Exception: undefined is not an object (evaluating 'e.length')', reason: 'Unhandled JS Exception: undefined is not an object (evaluating 'e.length')``` is a major blocker, do we need to open another issue for that here, or should we keep this one open?

**Comment by bnjm** [comment] 2017-11-08 16:28
@PvanHengel updating to RN `0.50.3` fixed this for me... hopefully fixes for you too.

**Comment by SSTPIERRE2** [comment] 2017-11-08 19:41
Upgrading to RN ``` 0.50.3 ``` fixed this same issue for me too! I hope upgrading fixes this for you all as well, and if you haven't done it before here's the doc: https://facebook.github.io/react-native/docs/upgrading.html cheers!

**Comment by JuliusMalisauskasDB** [comment] 2017-11-09 06:44
RN 0.50.3 does not fix that another issue: 
`Unhandled JS Exception: undefined is not an object (evaluating 'e.length')`

**Comment by PvanHengel** [comment] 2017-11-09 11:54
@JuliusMalisauskasDB see https://github.com/facebook/react-native/issues/16745 it is related to an issue which has been merged with the color-convert library.  I believe the fix was merged.

**Comment by rmevans9** [comment] 2017-11-11 01:51
@JuliusMalisauskasDB I resolved this issue with a `yarn` `resolution` to set `color-convert` to 1.9.1. There are a few libraries that seem to depend specifically on 1.9.0. For me it was `react-native-svg`

**Comment by DiederikvandenB** [comment] 2017-11-21 19:35
I'm on 0.50.3 and I am still experiencing this issue.

**Comment by flylxq** [comment] 2017-11-28 13:23
On 0.50.4 I am having this issue.
<img width="393" alt="b27493c0-ccaa-4671-ae19-a770232e1233" src="https://user-images.githubusercontent.com/5128600/33321895-434d44d6-d482-11e7-8131-c7fe37cdf5a3.png">

**Comment by rafeca** [comment] 2017-11-28 13:27
Can you check which version of metro-bundler are you using? To do so, check for the metro-bundler entry on your `yarn.lock` file.

This issue was fixed in `v0.20.2`

**Comment by nsipplswezey** [comment] 2017-12-01 07:28
Ran into the same error with a fresh clone+build of a previously functional project.
```
    "dependencies": {
        "react": "16.0.0",
        "react-native": "0.50.4"
    },
```

Did an `rm yarn.lock` and `rm package-lock.json` and an `npm i`.
Now my `package-lock.json` is:
```
        "metro-bundler": {                                                      
            "version": "0.20.3",
            "resolved": "https://registry.npmjs.org/metro-bundler/-/metro-bundler-0.20.3.tgz",
```

Though my `node_modules/react-native/package.json` shows
```
    "metro-bundler": "^0.20.1",  
```

Regardless I'm back up and running.
For anyone else stuck on this, my issue seemed to be an old yarn.lock file from maybe from an old `yarn install`, when currently I'm using `npm install`.

**Comment by rafeca** [comment] 2017-12-04 12:41
Thanks @nsipplswezey for shedding some light. In fact, package manager lock files will prevent updating to the metro version that fixed this issue (v0.20.1).

For anyone stumbling across this issue, remove the metro entry in your package-lock.json/yarn.lock file and `npm install`/`yarn install` again

**Comment by hqro** [comment] 2017-12-04 22:16
On RN0.50.4, with metro-bundle@0.20.3 I am having this issue.

**Comment by rafeca** [comment] 2017-12-05 12:30
@hqro are you sure that the metro version that you're using is 0.20.3? Can you post the whole error stack trace you're getting?

**Comment by hqro** [comment] 2017-12-06 14:00
@rafeca this is my `yarn.lock`

```
metro-bundler@^0.20.1, metro-bundler@^0.20.3:
  version "0.20.3"
  resolved "https://registry.yarnpkg.com/metro-bundler/-/metro-bundler-0.20.3.tgz#0ded01b64e8963117017b106f75b83cfc34f3656"
```

**Comment by albertobram** [comment] 2017-12-08 15:58
I am running into this issue as well, I have these versions of the components:
metro-bundler 0.20.3 
react 16.0.0
react-native 0.50.3

**Comment by janicduplessis** [comment] 2017-12-12 03:46
@rafeca Just hit this issue with metro@0.23.0. It only happens when generating a prod bundle. Looking at the bundle a module that uses process.env (in my case invariant) appears before the InitializeCore module. This causes it to be executed before process.env polyfill is setup. As a workaround I added `import 'InitializeCore';` at the top of my index.js and now it works.

**Comment by rafeca** [comment] 2017-12-13 13:53
Hey @janicduplessis! Are you trying it with RN master?

I cannot repro it in my silly sample RN app: https://github.com/rafeca/rn-test-app if you have some repro steps I can take a deeper look

**Comment by rafeca** [comment] 2017-12-13 14:34
Ok, I've just actually been able to reproduce it, a fix is coming

**Closed** 2017-12-13 16:31 UTC

**Comment by leai-jiang** [comment] 2018-01-11 08:30
Also have this issue on react-native 0.52

**Comment by fungilation** [comment] 2018-01-12 08:30
Works for me on 0.52.
