### ISSUE TITLE
Transformer for asset does not work

### ISSUE THREAD

**Issue by kruyvanna** [facebook/metro#176] opened 2018-05-30 04:28 UTC
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
I am trying to create a transformer that process .svg files.
Currently it only feed .js files to the transformer not .svg files 

**If the current behavior is a bug, please provide the steps to reproduce and a minimal repository on GitHub that we can `yarn install` and `yarn test`.**
1. yarn install
2. react-native run-ios / react-native run android
3. check metro packager log for .svg file (console.log from transformer. see [svg_transformer](https://github.com/kruyvanna/metro-asset-transformer-test/blob/master/svg_transformer.js#L19))

Minimal repository:
https://github.com/kruyvanna/metro-asset-transformer-test

**What is the expected behavior?**
transformer.transform get called with .svg file

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm version and operating system.**
i have rn-cli.config.js with the following content
```
module.exports = {  
  assetTransforms: true,
  getPlatforms: () => ["ios", "android"],
  getTransformModulePath() {  	        
    	return require.resolve('./svg_transformer')    
  },
  getAssetExts() {
    return ["svg"];
  }
};
```

node: v8.9.1
yarn: 1.7.0
npm: 5.6.0
react-native-cli: 2.0.1
react-native: 0.55.4

**Comment by kruyvanna** [comment] 2018-05-31 08:34
@rafeca Thanks for the detail instruction.
I will give it a try

**Comment by kristerkari** [comment] 2018-08-02 20:28
I created my own SVG transformer based on the same idea. It uses `.svgx` file extension instead of `.svg`, because loading `.svg` files through the transformer is not supported due to the reasons that @rafeca mentioned above. I'm planning to switch to using `.svg` as soon as it's supported in React Native/Metro.

https://github.com/kristerkari/react-native-svg-transformer

**Comment by rafeca** [comment] 2018-08-02 22:37
I just want to give an update since many things happened since I wrote that message in May: we've recently rewritten the Metro configuration loading logic (you can read about the new config [here](https://facebook.github.io/metro/docs/en/configuration)) so the limitation regarding the default assets does not exist anymore.

With latest Metro you can define the asset extensions that you want without having to care about the default ones, so please ignore most of my previous message 😄

**Comment by rafeca** [comment] 2018-08-02 22:42
Closing this issue since with the new Metro API it should be solved

**Closed by rafeca** 2018-08-02 22:42 UTC

**Comment by kristerkari** [comment] 2018-08-03 05:46
@rafeca I saw some Metro configuration changes in React Native's repo. Do you know if those are going to fix the issue on React Native's side?

**Comment by rafeca** [comment] 2018-08-03 09:30
Yes, they fix it

**Comment by kristerkari** [comment] 2018-08-24 21:19
I'm having problems to get the new Metro configuration to work.

I have been trying out the 0.57.0-rc.2 version of React Native, which also includes the new Metro config. I'm using a working 0.56.0 project as the base.

I've read the code changes from React Native's side and the update docs for Metro, and based on that my updated `rn-cli.config.js` for transforming SVG files looks like this:

```js
module.exports = {
  transformModulePath: require.resolve("react-native-svg-transformer"),
  resolver: {
    sourceExts: ["svg"]
  }
};
```

The new config however just makes Metro throw an error:

```
error: bundling failed: ReferenceError: SHA-1 for file /Users/kristerkari/Git/SVGDemo/index.js is not computed
    at DependencyGraph.getSha1 (/Users/kristerkari/Git/SVGDemo/node_modules/metro/src/node-haste/DependencyGraph.js:236:119)
    at /Users/kristerkari/Git/SVGDemo/node_modules/metro/src/Bundler.js:203:56
    at Generator.next (<anonymous>)
    at step (/Users/kristerkari/Git/SVGDemo/node_modules/metro/src/Bundler.js:11:657)
    at /Users/kristerkari/Git/SVGDemo/node_modules/metro/src/Bundler.js:11:817
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

@rafeca do you have any ideas why that might happen?

**Comment by rafeca** [comment] 2018-09-11 11:37
@kristerkari : this is usually caused by `watchFolders` not containing the folder of that file. `watchFolders` should be automatically configured to include the root of your app, so this error is weird... Can you try updating to the latest RC and check if this still happens?

**Comment by kristerkari** [comment] 2018-09-11 11:40
@rafeca it's still happening with rc4

**Comment by kristerkari** [comment] 2018-09-11 11:44
@rafeca Here are the changes and the branch if you want to have a look at it:
https://github.com/kristerkari/react-native-svg-example/pull/1

**Comment by rafeca** [comment] 2018-09-11 13:11
Oh I see now, the issue comes from the fact that making `sourceExts: ["svg"]` removes the default source extensions, so the bundler cannot find the JS files.

To fix this, you can get the default source extensions and just append `svg` from your Metro config:

```js
const {getDefaultConfig} = require('metro');

module.exports = (async () => {
  const {resolver: {sourceExts}} = await getDefaultConfig();

  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer'),
    },
    resolver: {
      sourceExts: [...sourceExts, 'svg'],
    },
  };
})();
```

I acknowledge that this is not very nice to type... @CompuIves could we make it easier to extend the config object?

**Comment by kristerkari** [comment] 2018-09-11 13:26
Would it be possible to have some config property that would just add the file extension to the default ones instead of replacing them? 

Would be great to keep the config as simple as my previous example:

```js
module.exports = {
  transformModulePath: require.resolve("react-native-svg-transformer"),
  resolver: {
    sourceExts: ["svg"]
  }
};
```

**Comment by kristerkari** [comment] 2018-09-11 18:01
I managed to get the `.svg` images to load in React Native! 

The config to do that is very verbose because I also need to modify `assetExts` no to include `svg` file extension:

```js
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();

  return {
    transformer: {
      babelTransformerPath: require.resolve("react-native-svg-transformer")
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== "svg"),
      sourceExts: [...sourceExts, "svg"]
    }
  };
})();
```

That's pretty difficult to understand for someone who is not familiar with Metro at all.

**Comment by isbirkan** [comment] 2018-10-19 11:37
Hi guys!

I am so glad I stumbled upon this issue. It managed to put me on the right track. I am trying to add .pb and .txt assets to my project for a tensorflow integration. The above configuration works, but it behaves strange in my case.

If I only add a single optional extension it works as expected, but if I try to add 2 it throws an error.

For example, the code below throws an error:
`
const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
  const {
    resolver: { assetExts }
  } = await getDefaultConfig();

  return {
    resolver: {
      assetExts: [...assetExts, 'pb', 'txt']
    }
  };
})();
`

And the error is:
`
error: bundling failed: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at FileStore.get (*path*\node_modules\metro-cache\src\stores\FileStore.js:26:19)
    at *path*\node_modules\metro-cache\src\Cache.js:76:40
    at Generator.next (<anonymous>)
    at step (*path*\node_modules\metro-cache\src\Cache.js:18:30)
    at *path*\node_modules\metro-cache\src\Cache.js:37:14
    at new Promise (<anonymous>)
    at *path*\node_modules\metro-cache\src\Cache.js:15:12
    at Cache.get (*path*\node_modules\metro-cache\src\Cache.js:102:7)
    at *path*\node_modules\metro\src\DeltaBundler\Transformer.js:166:34
`

If I remove one of the extensions:
`
assetExts: [...assetExts, 'pb']
`
the bundle is created, but I need both extensions in order to have the application working.

Maybe someone has/had a similar problem and can manage to help me.

**Comment by sometimescasey** [comment] 2018-11-05 00:10
@isbirkan I've been working on a similar project and the following works for me in `metro.config.js`:

```
module.exports = {
  resolver: {
    assetExts: ['pb', 'txt', 'jpg']
  }
}
```
I followed the documentation at https://facebook.github.io/metro/docs/en/configuration. Hope this helps.

**Comment by isbirkan** [comment] 2018-11-05 09:17
Hi @sometimescasey!

Thank you very much! It works! I have tried this in the past, but I think I omitted 'jpg' and since I know it was a default asset extension I just tried to extend the config as others have done before. But this is ok and since it works it is all I need.

**Comment by punksta** [comment] 2019-01-18 10:35
I have similar error when I enable ram bundle on android
```
 bundling failed: ReferenceError: SHA-1 for file /home/_/app/node_modules/metro/src/lib/polyfills/require.js is not computed
```
"metro-react-native-babel-preset": "^0.50.0",
"react-native": "0.57.8"

**Comment by stylehuan** [comment] 2019-02-28 09:58
+1

**Comment by idudinov** [comment] 2019-07-24 12:18
Hey guys!
I'm using `react-native-svg-transformer` with `metro.config.js` updated according to this issue and official documentation of the package. 
Today (literally) Metro started to skip `svg` files in my custom transformer (custom because I'm using the solution from here: https://github.com/kristerkari/react-native-css-modules/blob/master/docs/multiple-transformers.md#step-4-configure-transformer), so `svg` files got unresolved during bundling with the following error:

```
Unable to resolve module `../assets/images/welcome-screen-persona.svg` from `<...>/src/screens/WelcomeScreen.tsx`: The module `../assets/images/welcome-screen-persona.svg` could not be found from `<...>/src/screens/WelcomeScreen.tsx`. Indeed, none of these files exist:
  * `<...>/src/assets/images/welcome-screen-persona.svg(.native||.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.json|.native.expo.json|.expo.json|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `<...>/src/assets/images/welcome-screen-persona.svg/index(.native||.ios.expo.js|.native.expo.js|.expo.js|.ios.expo.ts|.native.expo.ts|.expo.ts|.ios.expo.tsx|.native.expo.tsx|.expo.tsx|.ios.expo.json|.native.expo.json|.expo.json|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
```

Here's my full `metrol.config.js`:

```javascript
const { resolve } = require('path');
const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
    const {
        resolver: { sourceExts, assetExts }
    } = await getDefaultConfig();

    return {
        projectRoot: resolve(__dirname),
        watchFolders: [
            resolve(__dirname, '../common'),
        ],
        transformer: {
            // that's my custom transformer in which I won't receive svg files
            babelTransformerPath: require.resolve('./metro.transformer.js'),
        },
        resolver: {
            // I've made sure extensions got updated
            assetExts: assetExts.filter(ext => ext !== "svg"),
            sourceExts: [...sourceExts, "svg"],
            // below is for using external common folder with shared code
            extraNodeModules: {
                common: resolve(__dirname, '../common'),
                mobx: resolve(__dirname, 'node_modules/mobx'),
                tslib: resolve(__dirname, 'node_modules/tslib'),
                '@babel/runtime': resolve(__dirname, 'node_modules/@babel/runtime'),
                'firebase': resolve(__dirname, 'node_modules/firebase'),
            },
        },
    };
})();
```

For reference, I'm using Expo SDK 33.

Please give me an idea what could go wrong! Thanks in advance!

**Comment by kristerkari** [comment] 2019-07-24 14:38
@idudinov Are you using the newest version of React Native? It seems that something has changed, so that the transformers are not working, but I have not had time yet to look at the problem.

**Comment by kristerkari** [comment] 2019-07-24 15:25
Oh sorry I just noticed that you wrote that you are using Expo 33

**Comment by idudinov** [comment] 2019-07-24 17:13
Just for reference, Expo 33 uses React Native 0.59.8.
I've just checked the last version of my codebase (2 days old) when I was able to build my app, and it doesn't work now! That makes my crazy. Will try to find out what else could change on my side since that happy time when everything works just great.

**Comment by idudinov** [comment] 2019-07-25 00:10
Also I've tried to replace `svg` to `svgx`, and just added it to `sourceExts`, but no luck – Metro still fails to resolve the file.

One thing I think of could change during these days – I've updated XCode to 10.3. Will try to check on macs with previous version of it.

**Comment by idudinov** [comment] 2019-07-25 09:43
Phew! Downgrading XCode did not help, but downgrading Expo CLI did. Replaced `3.0.x` with `2.21.2` and the problem has gone. Spent only a day to work around this! 😂

**Comment by fdagostino** [comment] 2019-08-01 18:14
> Phew! Downgrading XCode did not help, but downgrading Expo CLI did. Replaced `3.0.x` with `2.21.2` and the problem has gone. Spent only a day to work around this! 😂

Can confirm that doing the downgrading got the thing working.
Any lead on how to get this working on latest version of expo-cli?

**Comment by kristerkari** [comment] 2019-08-01 18:18
@idudinov @fdagostino the docs for `react-native-svg-transformer` have been updated to include the correct config for expo-cli 3.x https://github.com/kristerkari/react-native-svg-transformer#for-react-native-v057-or-newer--expo-sdk-v3100-or-newer

**Comment by fdagostino** [comment] 2019-08-01 18:32
> @idudinov @fdagostino the docs for `react-native-svg-transformer` have been updated to include the correct config for expo-cli 3.x https://github.com/kristerkari/react-native-svg-transformer#for-react-native-v057-or-newer--expo-sdk-v3100-or-newer

Thanks @kristerkari, worked fine!
