### ISSUE TITLE
metro-config sharedBlacklist regexp without scape "\"

### ISSUE THREAD

**Issue by micnguyen** [facebook/metro#513] opened 2020-01-27 05:46 UTC
This re-opens https://github.com/facebook/metro/issues/453 as the issue is still prevalent despite it being closed.

**Comment by alifarukm** [comment] 2020-02-13 20:17
Yes same issue for me #453 . I can solve with [stackoverflow](https://stackoverflow.com/questions/58120990/how-to-resolve-the-error-on-react-native-start/58122821#58122821). Is it possible solve permanently ?

**Comment by brentvatne** [comment] 2020-05-28 17:00
this can occur if you are using an old version of metro. if you provide a reproducible example then it will be possible to help, but otherwise there isn't much we can do.

**Comment by MichaReiser** [comment] 2020-10-13 08:35
This is a duplicate of #578 which contains more information. We're happy to merge a PR with the fix.

**Closed by MichaReiser** 2020-10-13 08:35 UTC
