### ISSUE TITLE
metro-config sharedBlacklist regexp without scape "\"

### ISSUE THREAD

**Issue by lucasfontesgaspareto** [facebook/metro#453] opened 2019-09-27 20:00 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When i try to run react-native start an error is outputed
```
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\Users\***\react\myApp\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (C:\Users\***\react\myApp\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:69:59)
    at getDefaultConfig (C:\Users\***\react\myApp\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:85:20)
    at load (C:\Users\***\react\myApp\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:121:25)
    at Object.runServer [as func] (C:\Users\***\react\myApp\node_modules\@react-native-community\cli\build\commands\server\runServer.js:82:58)
    at Command.handleAction (C:\Users\***\react\myApp\node_modules\@react-native-community\cli\build\cliEntry.js:160:21)
    at Command.listener (C:\Users\***\react\myApp\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (C:\Users\***\react\myApp\node_modules\commander\index.js:651:12)
```

**Please provide your exact Metro configuration and mention your Metro, node, yarn/npm - =-- - version and operating system.**
- See above for metro config.
- Windows 10 x64
- node v12.11.0
- npm@6.11.3
- metro@0.56.0
- metro-config@0.56.0

**Comment by halkliff** [comment] 2019-10-07 13:44
This bug is caused due to Node's parsing of regular expressions in Node versions >=12.11.0.

These regular expressions should be fixed without any compatibility issues with older Node versions...

**Comment by Leminur** [comment] 2019-10-07 18:44
12.11.0 did not work for me, only 12.10.0 managed to fix the error, weirdly.

**Comment by gabsrl** [comment] 2019-10-10 15:09
I was having the same problem. I was  using node version 12.11.1 . I've changed to the LTS version of node and now everything is working fine.

**Comment by huuchi207** [comment] 2019-10-19 14:44
> Try
> `npm install metro-core `

not work for me

**Comment by xunzhou** [comment] 2019-10-25 00:46
As mentioned on [stackoverflow](https://stackoverflow.com/a/58122821). 
Escaping '/' of `sharedBlacklist `
in `\node_modules\metro-config\src\defaults\blacklist.js` works for me on node v12.13.0

**Comment by dalgrande** [comment] 2019-10-26 16:37
@xunzhou That's worked very well for me in Windows 10. Thanks.

**Closed** 2019-10-29 18:59 UTC

**Comment by armohammadi56** [comment] 2019-11-01 11:05
I just got a similar error for the first time today. It appears in \node_modules\metro-config\src\defaults\blacklist.js, there is an invalid regular expression that needed changed. I changed the first expression under sharedBlacklist from:

var sharedBlacklist = [
  /node_modules[/\\]react[/\\]dist[/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

to:

var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

**Comment by ehsanR91** [comment] 2019-11-02 06:26
Same problem with me, fixed it from here :
https://stackoverflow.com/a/58122821

**Comment by gezginrocker** [comment] 2019-11-12 22:46
I wish this problem was fixed, I'm having it in every install.

**Comment by vincentk42** [comment] 2019-11-26 02:30
> I wish this problem was fixed, I'm having it in every install.

Same here.

**Comment by iamakashaher** [comment] 2019-12-05 11:41
Replace existing shareBlacklist with this:
```
var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];
```

**Comment by ukasyahrz** [comment] 2019-12-06 05:38
var sharedBlacklist = [
  /node_modules[\\]react[\\]dist[\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];

**Comment by Gucal** [comment] 2019-12-14 23:00
> Same problem with me, fixed it from here :
> https://stackoverflow.com/a/58122821

Worked this way
Is it possible to turn it into globals?
Or should each new project be modified?

**Comment by bluelovers** [comment] 2019-12-24 15:51
https://github.com/facebook/metro/issues/453

for who still get this error without official patch in react-native , expo
use yarn and add this setting into package.json

```json
{
  ...
  "resolutions": {
    "metro-config": "bluelovers/metro-config-hotfix-0.56.x"
  },
 ...
```

**Comment by dakkafex** [comment] 2019-12-28 05:36
why is this still an issue?!

**Comment by EliasKotlyar** [comment] 2019-12-31 22:01
Can report that i can reproduce it on a Win10 with a fresh installed react-native

**Comment by SaeedZhiany** [comment] 2020-01-07 08:12
Changing the regex manually seems not a good solution, because it will break on CI servers. I'm wondering why this issue has been closed without any proper solution.

**Comment by micnguyen** [comment] 2020-01-07 11:10
I can report that even on `0.57.0` with the supposed fix https://github.com/facebook/metro/commit/7c6f30b592b2fb23cee55b54f1aa4b7a522dec18 this is still a problem

**Comment by malFuckingFurion** [comment] 2020-01-10 13:36
This is caused by node v12.11.0.

To fix it go to:

`\node_modules\metro-config\src\defaults\blacklist.js`

and change:
`var sharedBlacklist = [
  /node_modules[/\\]react[/\\]dist[/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];`

To:
`var sharedBlacklist = [
  /node_modules[\/\\]react[\/\\]dist[\/\\].*/,
  /website\/node_modules\/.*/,
  /heapCapture\/bundle\.js/,
  /.*\/__tests__\/.*/
];`

**Comment by vladp** [comment] 2020-01-12 06:10
Not clear why this issue was closed.
I am using latest version of node Long Term supported release (LTS)
v12.14.1

Running up to date Windows 10.
using react-native 0.60 

The problem is there, and I do not think manual modification inside of node_modules is a solution.
This works for developer machines but not for automated build processes that are meant to use package-lock.json and install a 'reproducible build' env.

Is RN no longer supporting LTS node releases to do builds?

**Comment by Baterka** [comment] 2020-01-22 22:10
Still problem. Not fixed

**Comment by lorekadam** [comment] 2020-01-28 19:15
Recently I've upgraded node to 12.14.1 and this problem happend with my Expo app. 
First I've deleted node_modules and *.lock files, then I've installed newest version of expo-cli, then run yarn to install all my packages and it's working

**Comment by WiXSL** [comment] 2020-02-02 00:27
Same problem.
This solve it: https://github.com/facebook/metro/issues/453#issuecomment-568769943

NodeJs: v12.4.1
react-native v0.61.5

**Comment by likeanormaldude** [comment] 2020-04-02 19:14
> Try
> `npm install metro-core `

It worked man!

**Comment by rdgomt** [comment] 2020-04-13 19:35
Same problem here. Node v12.16.2

**Comment by adil-Pathan** [comment] 2020-04-15 08:14
metro-config folder under node_modules is missing. Then what is next solution ?

**Comment by shayanpaul91** [comment] 2020-07-01 16:46
for me it get resolved by downgrading the nodeJs version i tried with 8.17.0 and its working

**Comment by sparebytes** [comment] 2020-07-25 00:19
The *real* fix is in #578.

**Comment by javaing** [comment] 2020-09-21 05:42
Today is 21 September 2020, still need every react native user fix the string error by self

**Comment by javaing** [comment] 2020-09-21 08:58
> Today is 21 September 2020, still need every react native user fix the string error by self (already after npm update)

node_modules\metro-config\src\defaults
but now I found those codes from October 26 1985, seem should not angry :)

**Comment by joranbeasley** [comment] 2020-12-19 07:33
how is this still an issue? I dont understand? @devs why is this issue closed? theres multimple MR's that have been submitted it looks like to resolve this ... what is the reasoning behind not fixing this?

**Comment by halkliff** [comment] 2020-12-19 15:08
Wait, is it still up? Haven't it been fixed in the latest versions already?

**Comment by joranbeasley** [comment] 2020-12-19 20:53
Im not entirely sure ... all i know is i installed react-vr and it errored out with this message about bad regex and spent way longer than i wanted to trying to figure out what was wrong ... maybe react-vr is bundling an older version i guess in which case ill go nag them

**Comment by WiXSL** [comment] 2020-12-19 21:29
It seems they fix it in the latest release [v0.64.0](https://github.com/facebook/metro/releases/tag/v0.64.0)

`[Breaking]: Renames the Metro transform.inlineRequires.blacklist option to blockList. (b25fe89)`
`[Fix]: Correctly escape the path separator in blocklist regular expressions on Windows (881d9f6)`

**Comment by litotechenterprise** [comment] 2021-04-09 05:01
My blacklist.js file has been completely deleted... is there any way to find the entire file not just the regular expression that needs to be changed?

error Cannot find module 'metro-config/src/defaults/blacklist'

**Comment by sparebytes** [comment] 2021-04-09 05:31
@litotechenterprise, it's been renamed to exclusionList.js

https://github.com/facebook/metro/blob/a94200229df4e7f3a9549665142d4ad4b8d32de5/packages/metro-config/src/defaults/exclusionList.js

**Comment by niraj-khatiwada** [comment] 2021-05-15 09:18
For the folks still having issue. The blacklist.js has been renamed to exclusionList. So go to metro.config.js and replace the import from :
const blacklist = require('metro-config/src/defaults/blacklist');
to:
const blacklist = require('metro-config/src/defaults/exclusionList');

**Comment by Mihai-github** [comment] 2021-05-26 11:30
Hi, I have the latest version of react-native (the current one I am talking about is "react-native": "^0.64.1",) and from what I have read across all websites the universal solution is with changing in node_modules\metro-config\src\defaults\blacklist.js to change a variable..... but I don't have this file.... anyone has a different solution??

**Comment by aleksamrakovic** [comment] 2024-10-03 08:15
Anybody actually made blockList working?

in my case
`resolver: {
    blockList: new RegExp(/\/__mocks__\/.*/),
  },`
  
 i can still access these files on localhost:xxxx/__mocks__
